### PR TITLE
Support #if and #ifdef in if statements

### LINKED ISSUE #76: Seems 'function_definition' not parsed correctly when putting 'else-if' in '#ifndef'
I'm trying to extract all the function_definition in C files but seems there's a false positive for 'function_definition' query. 

Minimal repro:
```
int foo(int a)
{
    if (0)
        return 0;
    #ifndef XXX
    else if (1){
    	return 0;
    }
    #endif
}
```
```
translation_unit [0, 0] - [11, 0]
  function_definition [0, 0] - [9, 1]
    type: primitive_type [0, 0] - [0, 3]
    declarator: function_declarator [0, 4] - [0, 14]
      declarator: identifier [0, 4] - [0, 7]
      parameters: parameter_list [0, 7] - [0, 14]
        parameter_declaration [0, 8] - [0, 13]
          type: primitive_type [0, 8] - [0, 11]
          declarator: identifier [0, 12] - [0, 13]
    body: compound_statement [1, 0] - [9, 1]
      if_statement [2, 4] - [3, 17]
        condition: parenthesized_expression [2, 7] - [2, 10]
          number_literal [2, 8] - [2, 9]
        consequence: return_statement [3, 8] - [3, 17]
          number_literal [3, 15] - [3, 16]
      preproc_ifdef [4, 4] - [8, 10]
        name: identifier [4, 12] - [4, 15]
        function_definition [5, 4] - [7, 5]  -------------------- strange result as function_definition
          type: type_identifier [5, 4] - [5, 8]
          declarator: function_declarator [5, 9] - [5, 15]
            declarator: identifier [5, 9] - [5, 11]
            parameters: parameter_list [5, 12] - [5, 15]
              ERROR [5, 13] - [5, 14]
                number_literal [5, 13] - [5, 14]
          body: compound_statement [5, 15] - [7, 5]
            return_statement [6, 5] - [6, 14]
              number_literal [6, 12] - [6, 13]
```

query:
`(function_definition (function_declarator (identifier) (parameter_list) @params) @decl)`

image

I'm not sure if this behavior is expected, but what should I do to avoid this?

### PR DESCRIPTION
**Pull request by MarcelRobitaille**
Fixes #76 

I was not able to add more than `$.preproc_if_in_if_statement` and `$.preproc_ifdef_in_if_statement` to `_else_clause_preproc`. I got some conflicts. I am not very experienced in writing tree-sitter grammars.

### CODE REVIEW

**Comment by amaanq** [comment]
This is a sizable state count increase, and I don't think I really want to support this use case - this just opens the door for many other edge cases with preproc defines as well. Tree-sitter is just not going to handle every possible usage of  macros and/or preproc defines well

**Comment by MarcelRobitaille** [comment]
Thank you for your feedback.

Is there any state count where you would accept this? I got the state count down to 2594 and all of the tests (including the ones I added) pass.

**Comment by amaanq** [comment]
What's the large state count? But again, this still sets a precedence I don't like anyways, and might be even more harmful for C++ since that would need to be updated with these changes afterwards.

**Comment by MarcelRobitaille** [comment]
```cpp
#define LANGUAGE_VERSION 14
#define STATE_COUNT 2594
#define LARGE_STATE_COUNT 693
#define SYMBOL_COUNT 352
#define ALIAS_COUNT 3
#define TOKEN_COUNT 155
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 39
#define MAX_ALIAS_SEQUENCE_LENGTH 9
#define PRODUCTION_ID_COUNT 132
```

**Pull request closed without merging**
