### PR TITLE
allow identifiers in string concatentations

### PR DESCRIPTION
**Pull request by clason**
Resolves errors in strings of the form:

   ("failed in line %" PRIdLINENR)

### CODE REVIEW

**Comment by clason** [comment]
cherry-picked from https://github.com/nvim-treesitter/tree-sitter-c/pull/2 @lewis6991 @amaanq

**Review by amaanq — APPROVED** [review]

**Comment by amaanq** [comment]
@ahlinc would like your thoughts too

**Comment by ahlinc** [comment]
Screenshot from 2023-07-15 14-40-02

> @ahlinc would like your thoughts too

I'd also alias the `identifier` node to the same node that represent a string content between double quotes but unfortunately there is no one.

It make sense to a bellow additional fix on top of this PR:
```
diff --git i/grammar.js w/grammar.js
index 94e7f3d..b51cacd 100644
--- i/grammar.js
+++ w/grammar.js
@@ -1055,13 +1055,16 @@ module.exports = grammar({

     concatenated_string: $ => seq(
       $.string_literal,
-      repeat1(choice($.string_literal, $.identifier)),
+      repeat1(choice(
+   $.string_literal,
+   alias($.identifier, $.string),
+      )),
     ),

     string_literal: $ => seq(
       choice('L"', 'u"', 'U"', 'u8"', '"'),
       repeat(choice(
-        token.immediate(prec(1, /[^\\"\n]+/)),
+        alias(token.immediate(prec(1, /[^\\"\n]+/)), $.string),
         $.escape_sequence,
       )),
       '"',
```

**Comment by clason** [comment]
Does it really make sense for `PRIdLINENR` to be a `string`?

**Comment by amaanq** [comment]
Maybe `string_content` is better than `string`, but I don't think identifiers should be aliased to string in concatenations

**Comment by amaanq** [comment]
Also gotta get rid of the appveyor thing after this

**Comment by clason** [comment]
Used `tree-sitter test -u`; hope that's OK!

**Comment by amaanq** [comment]
Mentioned this earlier [here](https://github.com/tree-sitter/tree-sitter-typescript/pull/253), but the formatting of the header/test delimiters needs to not happen, it pollutes the diff

**Comment by clason** [comment]
Would it be acceptable for me to do a separate commit before the change to reformat the corpus? I think the convenience of using `tree-sitter test -u` is worth a single reformat churn.

**Comment by amaanq** [comment]
hmm not sure what you mean, like a commit of additional tests?

**Comment by clason** [comment]
like a commit _just_ calling `tree-sitter test -u` on the old parser to reformat everything (without additional changes), so that the next commit with the changes can use `tree-sitter test -u` to _only_ update the now failing tests, without polluting the diff.

**Comment by amaanq** [comment]
Oooh, yeah I'm way too tired my bad for not getting that - that would be nicer for the future

**Comment by ahlinc** [comment]
> but I don't think identifiers should be aliased to string in concatenations

@amaanq in concatenations identifiers aren't identifiers because they are concatenated literally and not by value.

**Comment by amaanq** [comment]
well it's like an identifier that holds a string, so it shouldn't be aliased as such so users can distinguish them imo

**Comment by ahlinc** [comment]
> well it's like an identifier that holds a string, so it shouldn't be aliased as such so users can distinguish them imo

sorry, my bad, `bash` in my mind.

**Comment by ahlinc** [comment]
Hmm, for the clarity may be it would still make sense to alias `identifier` to the `preproc_arg` for example, because it's not real C variable and in this place it's clear how it can appear in concatenation.

Screenshot from 2023-07-15 16-21-56

**Comment by amaanq** [comment]
> Preproc directives parsing definitely requires improvements.

Agreed..

**Pull request merged**
