### PR TITLE
Support optional consequences

### PR DESCRIPTION
**Pull request by amaanq**

### CODE REVIEW

**Comment by aryx** [comment]
I think you need to regenerate the parser.c code too.

**Comment by aryx** [comment]
Not sure why we don't have any CI check working for this repo. Also what is this appveyor thing?

**Comment by amaanq** [comment]
Whoops, added parser.c changes now. I can add a PR for CI checks as well later today

**Comment by aryx** [comment]
That would be great! We should just the same CI we have for the other tree-sitter-xxx repos. Not sure why tree-sitter-c got left behind.

**Review by aryx — APPROVED** [review]

**Pull request merged**
