### PR TITLE
Support attribute statements under case statements

### PR DESCRIPTION
**Pull request by jdrouhard**
Case statements need support for attributed statements as well to support `[[fallthrough]];` as a single statement under a case label.

### CODE REVIEW

**Comment by jdrouhard** [comment]
@maxbrunsfeld after merging this, can we get another minor release of tree-sitter-c? I made another update earlier that split out declaration_modifiers into a separate hidden node so I can override that from tree-sitter-cpp. I need that for some fixes to `virtual` handling. Cheers!

**Comment by maxbrunsfeld** [comment]
IMO, the `attributed_statement` node should be visible, so that the attributes are grouped with their corresponding statement.

👍  Glad you caught that case statement issue.

**Comment by jdrouhard** [comment]
Ok, I was going back and forth. I'll change it back to a named node.

**Comment by jdrouhard** [comment]
@maxbrunsfeld done. Let me know what you think and if you can make a minor release again? (sorry for all the trouble recently, I'm trying to fix a few things I've noticed in c and cpp in the past few months now that I'm using tree sitter more heavily in my daily use).

**Comment by maxbrunsfeld** [comment]
Thanks @jdrouhard. I’ll do the release when I get back home on Monday.

**Comment by maxbrunsfeld** [comment]
@jdrouhard I published 0.20.1 on npm and crates.io.

**Comment by jdrouhard** [comment]
Thanks @maxbrunsfeld, much appreciated!

**Pull request merged**
