### PR TITLE
fix: allow preproc define without value to preceed a line with whitespace

### PR DESCRIPTION
**Pull request by benjaminBrownlee**
Notice in the preprocessor test cases file, I modified one of the test cases to include a preprocessor define with no value followed by an indented line. This change innocuous change breaks the syntax tree. Before this fix, the first define would escape its line and consume the next line if it started with whitespace. Here is a minimal example in vim,

image

image

I am not sure why the use of `repeat1()` caused this behavior, but I have added a new regex rule which enforces that the value of a define begins with a non-whitespace character.

### CODE REVIEW

**Comment by benjaminBrownlee** [comment]
Rebased back up to master branch. Any maintainer have any opinion on this PR?

**Comment by amaanq** [comment]
seems fine, can you rebase again?

**Review by amaanq — APPROVED** [review]

**Comment by amaanq** [comment]
another example or two would be nice with varying levels of indents, but not totally needed..

**Comment by benjaminBrownlee** [comment]
Sorry I didn't see your request for more test cases. Thanks for merging this though!

**Pull request merged**
