### PR TITLE
Add Microsoft SEH extension to the grammar

### PR DESCRIPTION
**Pull request by DennySun2100**
This change is to make c/c++ parser be able to parse Microsoft SEH extension - __try/__except/__finally/__leave. Please refer to "SEH exception handling" in test/corpus/microsoft.txt for the test on this change.

### CODE REVIEW

**Review by DennySun2100 — COMMENTED** [review]
@amaanq Could you help look at this change, it is adding Microsoft SEH extension.

**Review by DennySun2020 — APPROVED** [review]

**Comment by amaanq** [comment]
Alright I collapsed it into one commit and tidied up the test, let me know if that looks good @DennySun2020

**Review by amaanq — APPROVED** [review]

**Comment by DennySun2100** [comment]
> e know if that lo
Thanks Amaan, that looks good to me, should I close this PR now? Looks like I have no write access to merge this change to main branch?

**Comment by amaanq** [comment]
no worries, was just letting you check it out then I'l merge

**Pull request merged**
